name: Auto Sync All Branches

on:
  schedule:
    - cron: '0 3 * * *'          # 每天 03:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. 取回自己 fork 的完整历史
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. 只做「快进」同步 main，不会覆盖你自己提交
      - name: Fast-forward main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh repo sync "${{ github.repository }}"

      # 3. 同步其余所有分支，排除 main，保留 -f 覆盖
      - name: Sync all other branches
        run: |
          set -e
          git remote add upstream https://github.com/Vespa314/chan.py.git
          git fetch upstream --prune
          for b in $(git for-each-ref --format='%(refname:strip=3)' refs/remotes/upstream | \
                     grep -v '^HEAD$' | grep -v '^main$'); do
            echo "▶ syncing $b"
            git push -f origin "refs/remotes/upstream/$b:refs/heads/$b"
          done
